---
homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - ack
  - autoconf
  - bash-completion
  - bat
  - chruby
  - ctags
  - doxygen
  - drush
  - fd
  - fzf
  - gettext
  - git
  - gpg
  - go
  - heroku/brew/heroku
  - htop
  - httpie
  - hub
  - iperf
  - jq
  - libdvdcss
  - libevent
  - mcrypt
  - mysql
  - ncdu
  - nmap
  - openssl
  - packer
  - pandoc
  - prettyping
  - pv
  - python
  - readline
  - reattach-to-user-namespace
  - sqlite
  - ssh-copy-id
  - tldr
  - tmux
  - tmate
  - wget
  - wrk
  - zsh
