---
dotfiles_repo: https://github.com/jeremy-hanna/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .tmux.conf
  - .osx
  - .vim
  - .vimrc
  - .zshrc
