---
downloads: ~/.ansible-downloads/

configure_sudoers: yes

dotfiles_repo: https://github.com/jeremy-hanna/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .tmux.conf
  - .osx
  - .vim
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - cowsay
  - chruby
  - doxygen
  - drush
  - gettext
  - git
  - gpg
  - httpie
  - hub
  - iperf
  - libdvdcss
  - libevent
  - mcrypt
  - mysql
  - nmap
  - openssl
  - packer
  - pv
  - python
  - readline
  - reattach-to-user-namespace
  - sqlite
  - ssh-copy-id
  - tmux
  - tmate
  - wget
  - wrk
  - zsh

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - boostnote
  - docker
  - dropbox
  - fing
  - flux
  - firefox
  - google-chrome
  - iterm2
  - karabiner-elements
  - licecap
  - limechat
  - yujitach-menumeters # Note: Using forked version for 10.11+ support
  - nvalt
  - skitch
  - slack
  - spotify
  - tunnelblick
  - vagrant
  - virtualbox
  - vlc
