---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml
    - group_vars/brew_config.yml
    - group_vars/brew_list.yml
    - group_vars/brew_cask_list.yml
    - group_vars/dotfiles.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles

  tasks:
    - include: tasks/ansible-setup.yml

    # install zplug if it is not already installed, not sure how to update it
    - name: Check for zplug
      stat: path=~/.zplug
      register: zplug_exists

    - name: Install zPlug for ZSH
      when: zplug_exists.stat.exists == false
      shell: curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh

    - name: Check for GoPath
      stat: path=~/src/go
      register: gopath

    - name: Build GoLang dir structure
      shell: mkdir -p ~/src/go/src/github.com/jeremy-hanna
      when: gopath.stat.exists == false

    # TODO: Use sudo once .osx can be run via root with no user interaction.
    - name: Run .osx dotfiles.
      shell: ~/.osx --no-restart
      changed_when: false
