---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles

  tasks:
    - include: tasks/ansible-setup.yml

    # install zplug if it is not already installed, not sure how to update it
    - name: Check for zplug
      shell: command -v zplug
      register: zplug_exists
      ignore_errors: yes

    - name: Install zPlug for ZSH
      shell: curl -sL zplug.sh/installer | zsh
      when: zplug_exists != 0

    # TODO: Use sudo once .osx can be run via root with no user interaction.
    - name: Run .osx dotfiles.
      shell: ~/.osx --no-restart
      changed_when: false
